### ISSUE TITLE
Unable to build on Expo SDK52

### ISSUE THREAD

**Issue by sweebee** [tr3v3r/react-native-esc-pos-printer#199]
### Description

When updating from SDK 51 to 52, I cant create a build anymore.

```
Android gradle plugin: 8.6.0
Gradle: 8.10.2

> Task :app:compileDebugJavaWithJavac FAILED
/Users/wiebe/Projecten/mijnepay_pos/android/app/build/generated/autolinking/src/main/java/com/facebook/react/PackageList.java:28: error: cannot find symbol
import com.escposprinter.EscPosPrinterPackage;
                        ^
  symbol:   class EscPosPrinterPackage
  location: package com.escposprinter
/Users/wiebe/Projecten/mijnepay_pos/android/app/build/generated/autolinking/src/main/java/com/facebook/react/PackageList.java:93: error: cannot find symbol
      new EscPosPrinterPackage(),
          ^
  symbol:   class EscPosPrinterPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 8s
```

### Steps to reproduce

Install this library
Run npx expo run:android

### react-native-esc-pos-printer version

4.3.0

### React Native version

0.76.3

### Platforms

Android

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Acknowledgements

Yes

**Comment by tr3v3r** [comment]
Hi @sweebee 

expo SDK 52 has enabled new architecture by default. Have you explicitly disabled it ?

**Comment by yushk** [comment]
> Hi @sweebee
> 
> expo SDK 52 has enabled new architecture by default. Have you explicitly disabled it ?

hi @tr3v3r 
i have same problem，how to disabled it？

**Comment by AnasRezk** [comment]
Hi @tr3v3r, 

Disabling newArchEnabled in app.json for Expo doesn’t seem to resolve the issue. Plus, I believe you might need to enable [the new architecture manually](https://docs.expo.dev/guides/new-architecture/#enable-the-new-architecture-in-an-existing-project).

**Comment by tr3v3r** [comment]
Should be fixed in the 4.3.1.

@sweebee @AnasRezk @yushk

**Comment by AnasRezk** [comment]
> Should be fixed in the 4.3.3.

I tested it with Expo and EAS Build, and it works. Thanks 💯 ❤️
