### ISSUE TITLE
ios version "1.3.0"  Undefined symbol: _OBJC_CLASS_$_Epos2BluetoothConnection

### ISSUE THREAD

**Issue by ahaikal** [tr3v3r/react-native-esc-pos-printer#30]
Hi, after upgrading to v1.3.0 on ios i'm getting this error

```
ld: warning: ignoring file ./node_modules/react-native-esc-pos-printer/ios/PrinterSDK/libepos2.a, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Epos2BluetoothConnection", referenced from:
      objc-class-ref in libreact-native-esc-pos-printer.a(EscPosPrinter.o)
  "_OBJC_CLASS_$_Epos2Discovery", referenced from:
      objc-class-ref in libreact-native-esc-pos-printer.a(EscPosPrinterDiscovery.o)
  "_OBJC_CLASS_$_Epos2FilterOption", referenced from:
      objc-class-ref in libreact-native-esc-pos-printer.a(EscPosPrinterDiscovery.o)
  "_OBJC_CLASS_$_Epos2Printer", referenced from:
      objc-class-ref in libreact-native-esc-pos-printer.a(EscPosPrinter.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_Epos2BluetoothConnection
Undefined symbol: _OBJC_CLASS_$_Epos2Discovery
Undefined symbol: _OBJC_CLASS_$_Epos2FilterOption
Undefined symbol: _OBJC_CLASS_$_Epos2Printer
``` 
android works fine.
